image: python:3.10-alpine

stages:
  - test

variables:
  MODE: "prod"
  POETRY_VERSION: 1.1.13

tests:
  stage: test
  only:
    - master
    - develop
    - merge_request
  script:
    - ln -s /root/.poetry/bin/poetry /usr/bin/poetry
    - wget https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
    - python3 ./get-poetry.py --version $POETRY_VERSION
    - poetry config virtualenvs.create false
    - poetry install
    - pytest
