repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.7"
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: poetry run mypy --show-error-codes
        types: [python]
        exclude: tests
