[tool.poetry]
name = "blog-generator"
version = "0.1.0"
description = ""
authors = ["Aleksey Petrunnik"]

[tool.poetry.dependencies]
python = "^3.10"
markdown = "^3.3"
pygments = "^2.11"
pymdown-extensions = "^9.3"
jinja2 = "^2.11"
markupsafe = "=2.0.1"  # Зафиксировал версию, чтобы jinja2 работал корректно
gitpython = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "=7.1.1"
pytest-datadir = "=1.3.1"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
