[tool.poetry]
name = "blog-generator"
version = "0.1.0"
description = ""
authors = ["Aleksey Petrunnik"]

[tool.poetry.dependencies]
python = "^3.7"
markdown = "^3.2"
pygments = "^2.4"
pymdown-extensions = "^7.1"
jinja2 = "^2.10"
gitpython = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
