name: tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

env:
  UV_VERSION: "0.9.9"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv sync
      - name: Run lint
        run: uv run pre-commit run --all

  test:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
